services:
  - type: web
    name: flask-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        value: dn5l0jh19
      - key: CLOUDINARY_API_KEY
        value: 741223792776498
      - key: CLOUDINARY_API_SECRET
        value: 36ODK08w5GkAd0UKekFkFt3QyXo
      - key: CLOUDINARY_UPLOAD_PRESET
        value: Papers
      - key: SESSION_SECRET
        value: your_secret_key
      - key: DATABASE_URL
        value: postgresql://papers_aly2_user:6JGPhFM3BnfnQ1tezHmFE7HeJXpKLwHw@dpg-d13ls20gjchc7390i32g-a.oregon-postgres.render.com/papers_aly2